// Generated by CoffeeScript 1.7.1
(function() {
  define(['underscore', 'marionette'], function(_, Marionette) {
    return Marionette.ItemView.extend({
      template: _.template('子节点')
    });
  });

}).call(this);
