// Generated by CoffeeScript 1.7.1
(function() {
  define(['underscore', 'backbone', 'components/tree/tree_node_model'], function(_, Backbone, TreeNode) {
    return Backbone.Collection.extend({
      model: TreeNode
    });
  });

}).call(this);
