// Generated by CoffeeScript 1.7.1
(function() {
  define(['underscore', 'marionette', 'backbone', 'app', 'apps/desks/todo/content_view'], function(_, Marionette, Backbone, App, ContentView) {
    var controller;
    controller = {
      TodoApp: function() {
        var contentview;
        contentview = new ContentView();
        App.pagecontent.show(contentview);
      }
    };
    return controller;
  });

}).call(this);
