// Generated by CoffeeScript 1.7.1
define(['app', 'marionette', 'apps/account/tabs/controller', 'apps/account/userlist/app', 'apps/account/orgtree/app'], function(App, Marionette, Controller, UserlistApp, OrgtreeApp) {
  var AccountApp;
  AccountApp = App.module('AccountApp', {
    startWithParent: false
  });
  AccountApp.on('start', function() {
    var controller;
    controller = new Controller();
    controller.showTabs(App.pagetabs);
    AccountApp.on('app:account:started', controller.setCurrentApp, controller);
  });
  AccountApp.on('stop', function() {
    App.pagetabs.reset();
    AccountApp.currentApp = '';
  });
  AccountApp.startSubApps = function(appName) {
    var currentApp;
    currentApp = App.module(appName);
    if (AccountApp.currentApp === currentApp) {
      return;
    }
    if (AccountApp.currentApp) {
      AccountApp.currentApp.stop();
    }
    AccountApp.currentApp = currentApp;
    currentApp.start();
    AccountApp.trigger('app:account:started', appName);
  };
  return AccountApp;
});
