// Generated by CoffeeScript 1.7.1
define(['app', 'marionette', 'apps/desks/todo/controller'], function(App, Marionette, Controller) {
  var TodoApp, TodoRouter;
  TodoApp = App.module('DesksApp.TodoApp', {
    startWithParent: false
  });
  TodoRouter = Marionette.AppRouter.extend({
    before: function() {
      App.startSubApp('DesksApp');
      App.DesksApp.startSubApps('DesksApp.TodoApp');
    },
    controller: Controller,
    appRoutes: {
      'desks-todo': 'TodoApp'
    }
  });
  App.addInitializer(function() {
    new TodoRouter();
  });
  return TodoApp;
});
