// Generated by CoffeeScript 1.7.1
(function() {
  define(['app', 'backbone'], function(App, Backbone) {
    var Entities;
    Entities = App.module('Entities');
    Entities.Collection = Backbone.Collection.extend();
  });

}).call(this);
