// Generated by CoffeeScript 1.7.1
(function() {
  define(['underscore', 'marionette', 'app', 'apps/account/userlist/content_view'], function(_, Marionette, App, ContentView) {
    var Controller;
    Controller = {
      UserlistApp: function() {
        var contentview;
        contentview = new ContentView();
        App.pagecontent.show(contentview);
        App.pageleft.close();
        App.pageright.close();
      }
    };
    return Controller;
  });

}).call(this);
