// Generated by CoffeeScript 1.7.1
(function() {
  define(['underscore', 'marionette', 'text!apps/account/userlist/tmpl/content.html'], function(_, Marionette, templates) {
    return Marionette.ItemView.extend({
      template: _.template(templates)
    });
  });

}).call(this);
