// Generated by CoffeeScript 1.7.1
define(['app', 'backbone', 'entities/_base/collections', 'entities/_base/models'], function(App, Backbone, EntitiesCollections, EntitiesModels) {
  var API, NavModel, NavbarCollection;
  NavModel = App.Entities.Model.extend();
  NavbarCollection = App.Entities.Collection.extend({
    model: NavModel,
    url: 'api/navbar.json'
  });
  API = {
    getAll: function() {
      var deferred;
      deferred = $.Deferred();
      this._getNavbar(function(navbarCollection) {
        return deferred.resolve(navbarCollection);
      });
      return deferred.promise();
    },
    _getNavbar: function(callback) {
      var navbarCollection;
      navbarCollection = new NavbarCollection();
      navbarCollection.on('reset', callback);
      return navbarCollection.fetch({
        reset: true
      });
    }
  };
  return App.reqres.setHandler('navbar:entities', function() {
    return API.getAll();
  });
});
