// Generated by CoffeeScript 1.7.1
define(['app'], function(App) {
  var API;
  API = {
    getAll: function(url) {
      var deferred;
      deferred = $.Deferred();
      this._getTree((function(data) {
        return deferred.resolve(data);
      }), url);
      return deferred.promise();
    },
    _getTree: function(callback, url) {
      return $.get(url, function(data) {
        return callback(eval(data));
      });
    }
  };
  return App.reqres.setHandler('orgtree:entities', function(url) {
    return API.getAll(url);
  });
});
