// Generated by CoffeeScript 1.7.1
(function() {
  define(['app', 'marionette', 'apps/desks/disk/controller'], function(App, Marionette, Controller) {
    var DiskApp, DiskRouter;
    DiskApp = App.module('DesksApp.DiskApp', {
      startWithParent: false
    });
    DiskApp.on('stop', function() {
      App.pageright.reset();
    });
    DiskRouter = Marionette.AppRouter.extend({
      before: function() {
        App.startSubApp('DesksApp');
        App.DesksApp.startSubApps('DesksApp.DiskApp');
      },
      controller: Controller,
      appRoutes: {
        'desks-disk': 'DiskApp'
      }
    });
    App.addInitializer(function() {
      new DiskRouter();
    });
    return DiskApp;
  });

}).call(this);
