// Generated by CoffeeScript 1.7.1
(function() {
  define(['backbone'], function(Backbone) {
    return Backbone.Model.extend({
      defaults: '',
      title: '',
      admin: '',
      tag: '',
      size: '',
      update: ''
    });
  });

}).call(this);
