// Generated by CoffeeScript 1.7.1
define(['underscore', 'marionette', 'app', 'apps/account/userlist/content_view'], function(_, Marionette, App, ContentView) {
  var Controller;
  return Controller = {
    UserlistApp: function() {
      var contentview;
      contentview = new ContentView();
      App.pagecontent.show(contentview);
      App.pageleft.close();
      return App.pageright.close();
    }
  };
});
