// Generated by CoffeeScript 1.7.1
define(['underscore', 'marionette', 'backbone', 'navbar/layout_view', 'navbar/left_view', 'navbar/right_view'], function(_, Marionette, Backbone, LayoutView, LeftView, RightView) {
  var Controller;
  Controller = Marionette.Controller.extend({
    showNavbar: function(regions) {
      var App, func;
      this.regions = regions;
      func = _.bind(this._showNavbar, this);
      App = require('app');
      $.when(App.request('navbar:entities')).then(func);
    },
    _showNavbar: function(navbarCollection) {
      var layoutview, rightview;
      layoutview = new LayoutView();
      this.leftview = new LeftView({
        collection: navbarCollection
      });
      rightview = new RightView();
      this.regions.show(layoutview);
      layoutview.left.show(this.leftview);
      layoutview.right.show(rightview);
      this.leftview.setCurrent(this.selected_app);
    },
    setCurrentApp: function(appName) {
      this.selected_app = appName;
      if (this.leftview) {
        return this.leftview.setCurrent(appName);
      }
    }
  });
  return Controller;
});
