// Generated by CoffeeScript 1.7.1
define(['backbone'], function(Backbone) {
  return Backbone.Model.extend({
    defaults: {
      title: '',
      admin: '',
      tag: '',
      size: '',
      update: ''
    }
  });
});
