// Generated by CoffeeScript 1.7.1
define(['underscore', 'marionette', 'text!apps/desks/disk/tmpl/form.html'], function(_, Marionette, FormTemplate) {
  return Marionette.ItemView.extend({
    className: 'modal-dialog',
    template: _.template(FormTemplate),
    templateHelpers: {
      getTitle: function() {
        if (true) {
          return '新建文件夹';
        } else {
          return '上传文件';
        }
      }
    },
    triggers: {
      submit: 'file:save'
    }
  });
});
