// Generated by CoffeeScript 1.7.1
define(['underscore', 'marionette', 'backbone', 'apps/desks/page_nav/left_view'], function(_, Marionette, Backbone, LeftView) {
  var Controller;
  return Controller = Marionette.Controller.extend({
    showPageNav: function(regions) {
      this.leftview = new LeftView();
      return regions.show(this.leftview);
    },
    setCurrentApp: function(appName) {
      return this.leftview.setCurrent(appName);
    }
  });
});
