// Generated by CoffeeScript 1.7.1
define(['underscore', 'marionette', 'text!apps/desks/page_nav/tmpl/left.html'], function(_, Marionette, LeftTemplates) {
  return Marionette.ItemView.extend({
    template: _.template(LeftTemplates),
    setCurrent: function(appName) {
      appName = appName.replace('.', '-');
      return $('#' + appName).tab('show');
    }
  });
});
