// Generated by CoffeeScript 1.7.1
(function() {
  define(['underscore', 'marionette', 'text!navbar/tmpl/item.html'], function(_, Marionette, ItemTemplate) {
    return Marionette.ItemView.extend({
      tagName: 'li',
      template: _.template(ItemTemplate)
    });
  });

}).call(this);
