// Generated by CoffeeScript 1.7.1
(function() {
  define(['underscore', 'marionette', 'text!navbar/tmpl/layout.html'], function(_, Marionette, LayoutTemplate) {
    return Marionette.Layout.extend({
      template: _.template(LayoutTemplate),
      regions: {
        left: '#nav-left',
        right: '#nav-right'
      }
    });
  });

}).call(this);
