// Generated by CoffeeScript 1.7.1
(function() {
  define(['underscore', 'marionette', 'text!navbar/tmpl/left.html', 'navbar/item_view'], function(_, Marionette, LeftTemplate, Itemview) {
    return Marionette.CompositeView.extend({
      template: _.template(LeftTemplate),
      itemView: Itemview,
      appendHtml: function(collectionView, itemView, index) {
        if (index < 3) {
          collectionView.$('.dropdown').before(itemView.el);
        } else {
          collectionView.$('.dropdown-menu').append(itemView.el);
        }
        if (index === 3) {
          collectionView.$('.dropdown').removeClass('hidden');
        }
      },
      setCurrent: function(appName) {
        $('#navbar li').removeClass('active');
        $('#' + appName).tab('show');
      }
    });
  });

}).call(this);
