// Generated by CoffeeScript 1.7.1
define(['app', 'backbone'], function(App, Backbone) {
  var Entities;
  Entities = App.module('Entities');
  return Entities.Collection = Backbone.Collection.extend();
});
