// Generated by CoffeeScript 1.7.1
define(['underscore', 'marionette', 'text!apps/sales/tabs/tmpl/tabs.html'], function(_, Marionette, TabsTemplate) {
  return Marionette.ItemView.extend({
    template: _.template(TabsTemplate),
    setCurrent: function(appName) {
      appName = appName.replace('.', '-');
      return $('#tabs-' + appName).tab('show');
    }
  });
});
