// Generated by CoffeeScript 1.7.1
define(['backbone', 'marionette', 'navbar/controller'], function(Backbone, Marionette, NavController) {
  var App, ModalRegion;
  App = new Marionette.Application();
  ModalRegion = Marionette.Region.extend({
    el: '#modal',
    onShow: function(view) {
      view.on('close', this.hideModal, this);
      return this.$el.modal('show');
    },
    hideModal: function() {
      return this.$el.modal('hide');
    }
  });
  App.addRegions({
    navbar: '#navbar',
    pagetabs: '#page-tabs',
    pageleft: '#page-left',
    pagecontent: '#page-content',
    pageright: '#page-right',
    modal: ModalRegion
  });
  App.pageleft.on('before:show', function(view) {
    return $('#page-left').removeClass('hidden');
  });
  App.pageright.on('before:show', function(view) {
    return $('#page-right').removeClass('hidden');
  });
  App.addInitializer(function() {
    var navController;
    navController = new NavController();
    navController.showNavbar(App.navbar);
    return App.vent.on('app:started', navController.setCurrentApp, navController);
  });
  App.on('initialize:after', function() {
    if (Backbone.history) {
      return Backbone.history.start();
    }
  });
  App.startSubApp = function(appName, args) {
    var currentApp;
    currentApp = App.module(appName);
    if (App.currentApp === currentApp) {
      return;
    }
    if (App.currentApp) {
      App.currentApp.stop();
    }
    App.currentApp = currentApp;
    currentApp.start(args);
    return App.vent.trigger('app:started', appName);
  };
  return App;
});
