// Generated by CoffeeScript 1.7.1
require.config({
  deps: ['app'],
  paths: {
    libs: 'libs',
    text: 'libs/text',
    jquery: 'libs/jquery',
    underscore: 'libs/underscore',
    backbone: 'libs/backbone',
    marionette: 'libs/backbone.marionette',
    bootstrap: 'libs/bootstrap',
    localStorage: 'libs/backbone.localStorage',
    babysitter: 'libs/backbone.babysitter',
    compute: 'libs/backbone.compute',
    routefilter: 'libs/backbone.routefilter'
  },
  shim: {
    underscore: {
      exports: '_',
      init: function() {
        this._.templateSettings = {
          evaluate: /\{\{#([\s\S]+?)\}\}/g,
          interpolate: /\{\{[^#\{]([\s\S]+?)[^\}]\}\}/g,
          escape: /\{\{\{([\s\S]+?)\}\}\}/g
        };
        return _;
      }
    },
    backbone: {
      deps: ['underscore', 'jquery'],
      exports: 'Backbone'
    },
    marionette: {
      deps: ['backbone', 'localStorage', 'routefilter'],
      exports: 'Marionette'
    },
    bootstrap: {
      deps: ['jquery']
    }
  }
});

require(['backbone', 'underscore', 'bootstrap', 'app', 'entities/navbar', 'entities/orgtree', 'apps/desks/app', 'apps/sales/app', 'apps/account/app'], function(Backbone, _, bootstrap, App, NavbarEntities, DesksApp, SalesApp, AccountApp) {
  require(['compute']);
  return App.start();
});
