// Generated by CoffeeScript 1.7.1
(function() {
  define(['underscore', 'marionette', 'backbone', 'apps/sales/tabs/tabs_view'], function(_, Marionette, Backbone, TabsView) {
    var Controller;
    Controller = Marionette.Controller.extend({
      showTabs: function(regions) {
        this.tabsview = new TabsView();
        regions.show(this.tabsview);
      },
      setCurrentApp: function(appName) {
        this.tabsview.setCurrent(appName);
      }
    });
    return Controller;
  });

}).call(this);
