// Generated by CoffeeScript 1.7.1
define(['underscore', 'marionette', 'components/tree/nav_node_view'], function(_, Marionette, NavNodeView) {
  return Marionette.CollectionView.extend({
    initialize: function(options) {
      return this.controller = options.controller;
    },
    className: 'navtree',
    itemView: NavNodeView,
    itemViewOptions: function() {
      return {
        controller: this.controller
      };
    },
    collapse: function() {
      return $(this.el).find('li > ul').hide();
    },
    loadCss: function(url) {
      var link;
      link = document.createElement('link');
      link.type = 'text/css';
      link.rel = 'stylesheet';
      link.href = url;
      return document.getElementsByTagName('head')[0].appendChild(link);
    }
  });
});
