// Generated by CoffeeScript 1.7.1
define(['underscore', 'backbone', 'components/tree/tree_node_model'], function(_, Backbone, TreeNode) {
  return Backbone.Collection.extend({
    model: TreeNode
  });
});
